# fly.toml file generated for neodb on 2022-12-18T21:23:49-05:00

app = "neodb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[deploy]
  release_command = "bash -c \"python manage.py migrate && python manage.py collectstatic --noinput\""

[env]
  PORT = "8080"
  new_data_model = "1"
  DJANGO_SETTINGS_MODULE = "boofilsic.fly"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[statics]]
  guest_path = "/workspace/static"
  url_prefix = "/static"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app", "rq"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
